version: '3.8'

services:
  backend:
    build: .
    container_name: skin_analysis_backend
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./models_cache:/root/.cache/huggingface
    restart: always
